### ISSUE TITLE
12/3110 domains invalid in global-anti-scam-org-scam-urls.txt (according to Pi-hole)

### ISSUE THREAD

**Issue by SystemJargon** [elliotwutingfeng/GlobalAntiScamOrg-blocklist#55]
Hi,

re file: /main/global-anti-scam-org-scam-urls.txt in this repo.

Pi-hole reports via Gravity pull/update;

```  [i] Analyzed 3110 domains, 12 domains invalid!
      Sample of invalid domains:
      - 103.193.243.225:365
      - 154.213.18.187:84
      - 35901125.com:9999
      - 38894435.kvbkunlun.vip:8967
      - 46639989.iui30.com:8967
```

I'd suggest removing the port numbers which I suspect is the issue pi-hole isn't happy about.

I'd say a simple regex of ```:[\d]+$``` would do the trick to strip out the port numbers at the end (find with regex string and replace with nothing)

If you need a hand with some regex, DM me or see my [regex simple repo](https://github.com/SystemJargon/regex/blob/main/regex-urls-domains.md).

p.s love your work and lists 👍🏼

**Comment by elliotwutingfeng** [comment]
Thanks for the feedback. I've added a pihole compatible list.

**Comment by SystemJargon** [comment]
Thanks :)
